// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdfdwvuqdmjgecuqrobd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkZmR3dnVxZG1qZ2VjdXFyb2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1MTc4NjMsImV4cCI6MjA4NjA5Mzg2M30.N-kUhWJaTIC--bOrFLhFts5VGOcVo0LtxbeCGK2j8kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});